package cli

// Mutating operation table for packet 3 coverage, derived from
// api/operations.json (the pinned OpenAPI inventory). write_ops_test.go fails
// if this table drifts from the inventory or leaves a non-GET operation
// uncovered. Two presigned/base64 upload operations use dedicated commands and
// are listed in fullyCoveredOperations; browser-navigation GET operations use
// dedicated URL-handoff commands.

// writeSpecs maps every implemented mutating operation to a CLI command.
var writeSpecs = []writeSpec{
	{
		group: "activity", action: "create",
		short:       "Create activity",
		operationID: "createActivity", method: "POST",
		path: "/activity/create",
		body: true,
	},
	{
		group: "activity", action: "create-comment",
		short:       "Create comment",
		operationID: "createComment", method: "POST",
		path: "/activity/comment",
		body: true,
	},
	{
		group: "activity", action: "delete-comment",
		short:       "Delete comment",
		operationID: "deleteComment", method: "DELETE",
		path:        "/activity/comment",
		body:        true,
		destructive: true,
	},
	{
		group: "activity", action: "update-comment",
		short:       "Update comment",
		operationID: "updateComment", method: "PUT",
		path: "/activity/comment",
		body: true,
	},
	{
		group: "column", action: "create",
		short:       "Create column",
		operationID: "createColumn", method: "POST",
		path: "/column/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "column", action: "delete",
		short:       "Delete column",
		operationID: "deleteColumn", method: "DELETE",
		path:        "/column/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "column", action: "reorder",
		short:       "Reorder columns",
		operationID: "reorderColumns", method: "PUT",
		path: "/column/reorder/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "column", action: "update",
		short:       "Update column",
		operationID: "updateColumn", method: "PUT",
		path: "/column/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "comment", action: "create-task",
		short:       "Create task comment",
		operationID: "createTaskComment", method: "POST",
		path: "/comment/{taskId}",
		body: true,
		params: []readParam{
			{name: "taskId", in: paramPath, flag: "task-id", required: true},
		},
	},
	{
		group: "comment", action: "delete",
		short:       "Delete task comment",
		operationID: "deleteTaskComment", method: "DELETE",
		path:        "/comment/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "comment", action: "update",
		short:       "Update task comment",
		operationID: "updateTaskComment", method: "PUT",
		path: "/comment/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "custom-field", action: "create",
		short:       "Create custom field",
		operationID: "createCustomField", method: "POST",
		path: "/custom-field",
		body: true,
	},
	{
		group: "custom-field", action: "delete",
		short:       "Delete custom field",
		operationID: "deleteCustomField", method: "DELETE",
		path:        "/custom-field/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "custom-field", action: "reorder-project",
		short:       "Reorder custom fields",
		operationID: "reorderCustomFields", method: "PUT",
		path: "/custom-field/reorder/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "custom-field", action: "set-value",
		short:       "Set custom field value",
		operationID: "setCustomFieldValue", method: "PUT",
		path: "/custom-field/value",
		body: true,
	},
	{
		group: "discord", action: "create-integration",
		short:       "Create Discord integration",
		operationID: "createDiscordIntegration", method: "POST",
		path: "/discord-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "discord", action: "delete-integration",
		short:       "Delete Discord integration",
		operationID: "deleteDiscordIntegration", method: "DELETE",
		path:        "/discord-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "discord", action: "update-integration",
		short:       "Update Discord integration",
		operationID: "updateDiscordIntegration", method: "PATCH",
		path: "/discord-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitea", action: "create-integration",
		short:       "Create Gitea integration",
		operationID: "createGiteaIntegration", method: "POST",
		path: "/gitea-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitea", action: "delete-integration",
		short:       "Delete Gitea integration",
		operationID: "deleteGiteaIntegration", method: "DELETE",
		path:        "/gitea-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitea", action: "import-issues",
		short:       "Import Gitea issues",
		operationID: "importGiteaIssues", method: "POST",
		path:  "/gitea-integration/import-issues",
		body:  true,
		notes: `Requires task:update permission in addition to task:create.`,
	},
	{
		group: "gitea", action: "list-repositories",
		short:       "List Gitea repositories",
		operationID: "listGiteaRepositories", method: "POST",
		path: "/gitea-integration/repositories",
		body: true,
	},
	{
		group: "gitea", action: "update-integration",
		short:       "Update Gitea integration",
		operationID: "updateGiteaIntegration", method: "PATCH",
		path: "/gitea-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitea", action: "verify-access",
		short:       "Verify Gitea access",
		operationID: "verifyGiteaAccess", method: "POST",
		path: "/gitea-integration/verify",
		body: true,
	},
	{
		group: "github", action: "create-integration",
		short:       "Create GitHub integration",
		operationID: "createGitHubIntegration", method: "POST",
		path: "/github-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "github", action: "delete-integration",
		short:       "Delete GitHub integration",
		operationID: "deleteGitHubIntegration", method: "DELETE",
		path:        "/github-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "github", action: "import-issues",
		short:       "Import GitHub issues",
		operationID: "importGitHubIssues", method: "POST",
		path:  "/github-integration/import-issues",
		body:  true,
		notes: `Requires task:update permission in addition to task:create. The server may stop before every issue is imported and report saved progress (HTTP 202, or "pending": true). The command then prints the complete result on stdout and exits 5 with error code "incomplete"; repeat it with the returned runId in the request body to continue.`,
	},
	{
		group: "github", action: "update-integration",
		short:       "Update GitHub integration",
		operationID: "updateGitHubIntegration", method: "PATCH",
		path: "/github-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "github", action: "verify-installation",
		short:       "Verify GitHub installation",
		operationID: "verifyGitHubInstallation", method: "POST",
		path: "/github-integration/verify",
		body: true,
	},
	{
		group: "label", action: "attach-task",
		short:       "Attach label to task",
		operationID: "attachLabelToTask", method: "PUT",
		path: "/label/{id}/task",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true, help: "Label ID"},
		},
	},
	{
		group: "label", action: "create",
		short:       "Create label",
		operationID: "createLabel", method: "POST",
		path: "/label",
		body: true,
	},
	{
		group: "label", action: "delete",
		short:       "Delete label",
		operationID: "deleteLabel", method: "DELETE",
		path:        "/label/{id}",
		destructive: true,
		notes:       `A large label may be removed in batches. When the server reports that more batches remain (HTTP 202), the command prints the response on stdout and exits 5 with error code "incomplete"; repeat the same command to continue.`,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true, help: "Label ID"},
		},
	},
	{
		group: "label", action: "detach-task",
		short:       "Detach label from task",
		operationID: "detachLabelFromTask", method: "DELETE",
		path:        "/label/{id}/task",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true, help: "Label ID"},
		},
	},
	{
		group: "label", action: "update",
		short:       "Update label",
		operationID: "updateLabel", method: "PUT",
		path: "/label/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true, help: "Label ID"},
		},
	},
	{
		group: "mattermost", action: "create-integration",
		short:       "Create Mattermost integration",
		operationID: "createMattermostIntegration", method: "POST",
		path: "/mattermost-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "mattermost", action: "delete-integration",
		short:       "Delete Mattermost integration",
		operationID: "deleteMattermostIntegration", method: "DELETE",
		path:        "/mattermost-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "mattermost", action: "update-integration",
		short:       "Update Mattermost integration",
		operationID: "updateMattermostIntegration", method: "PATCH",
		path: "/mattermost-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "mcp", action: "decide-authorization-request",
		short:       "Decide consent request",
		operationID: "decideMcpAuthorizationRequest", method: "POST",
		path: "/mcp/authorize/request/{requestId}",
		body: true,
		params: []readParam{
			{name: "requestId", in: paramPath, flag: "request-id", required: true, minLen: 1, maxLen: 128},
		},
	},
	{
		group: "mcp", action: "register-oauth-client",
		short:       "Register MCP OAuth client",
		operationID: "registerMcpOAuthClient", method: "POST",
		path:   "/mcp/register",
		public: true,
		body:   true,
	},
	{
		group: "notification", action: "clear-all",
		short:       "Clear all",
		operationID: "clearAllNotifications", method: "DELETE",
		path:        "/notification/clear-all",
		destructive: true,
		params: []readParam{
			{name: "workspaceId", in: paramQuery, flag: "workspace-id", minLen: 1, help: "Limit to this workspace plus user-wide notifications; omit for all workspaces"},
		},
	},
	{
		group: "notification", action: "create",
		short:       "Create notification",
		operationID: "createNotification", method: "POST",
		path: "/notification",
		body: true,
	},
	{
		group: "notification", action: "mark-all-read",
		short:       "Mark all read",
		operationID: "markAllNotificationsAsRead", method: "PATCH",
		path: "/notification/read-all",
		params: []readParam{
			{name: "workspaceId", in: paramQuery, flag: "workspace-id", minLen: 1, help: "Limit to this workspace plus user-wide notifications; omit for all workspaces"},
		},
	},
	{
		group: "notification", action: "mark-read",
		short:       "Mark notification read",
		operationID: "markNotificationAsRead", method: "PATCH",
		path: "/notification/{id}/read",
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "notification-preference", action: "delete-workspace-rule",
		short:       "Delete workspace rule",
		operationID: "deleteNotificationPreferenceWorkspaceRule", method: "DELETE",
		path:        "/notification-preferences/workspaces/{workspaceId}",
		destructive: true,
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
		},
	},
	{
		group: "notification-preference", action: "update",
		short:       "Update notification preferences",
		operationID: "updateNotificationPreferences", method: "PUT",
		path: "/notification-preferences",
		body: true,
	},
	{
		group: "notification-preference", action: "upsert-workspace-rule",
		short:       "Upsert workspace rule",
		operationID: "upsertNotificationPreferenceWorkspaceRule", method: "PUT",
		path: "/notification-preferences/workspaces/{workspaceId}",
		body: true,
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
		},
	},
	{
		group: "org", action: "accept-invitation",
		short:       "Accept Organization Invitation",
		operationID: "acceptOrganizationInvitation", method: "POST",
		path: "/auth/organization/accept-invitation",
		body: true,
	},
	{
		group: "org", action: "add-team-member",
		short:       "Add Organization Team Member",
		operationID: "addOrganizationTeamMember", method: "POST",
		path: "/auth/organization/add-team-member",
		body: true,
	},
	{
		group: "org", action: "cancel-invitation",
		short:       "Cancel Organization Invitation",
		operationID: "cancelOrganizationInvitation", method: "POST",
		path:        "/auth/organization/cancel-invitation",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "check-permission",
		short:       "Check Organization Permission",
		operationID: "hasOrganizationPermission", method: "POST",
		path: "/auth/organization/has-permission",
		body: true,
	},
	{
		group: "org", action: "check-slug",
		short:       "Check Organization Slug",
		operationID: "checkOrganizationSlug", method: "POST",
		path: "/auth/organization/check-slug",
		body: true,
	},
	{
		group: "org", action: "create",
		short:       "Create Organization",
		operationID: "createOrganization", method: "POST",
		path: "/auth/organization/create",
		body: true,
	},
	{
		group: "org", action: "create-role",
		short:       "Create Organization Role",
		operationID: "createOrganizationRole", method: "POST",
		path: "/auth/organization/create-role",
		body: true,
	},
	{
		group: "org", action: "create-team",
		short:       "Create Organization Team",
		operationID: "createOrganizationTeam", method: "POST",
		path: "/auth/organization/create-team",
		body: true,
	},
	{
		group: "org", action: "delete",
		short:       "Delete Organization",
		operationID: "deleteOrganization", method: "POST",
		path:        "/auth/organization/delete",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "delete-role",
		short:       "Delete Organization Role",
		operationID: "deleteOrganizationRole", method: "POST",
		path:        "/auth/organization/delete-role",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "invite-member",
		short:       "Invite Organization Member",
		operationID: "inviteOrganizationMember", method: "POST",
		path: "/auth/organization/invite-member",
		body: true,
	},
	{
		group: "org", action: "leave",
		short:       "Leave Organization",
		operationID: "leaveOrganization", method: "POST",
		path:        "/auth/organization/leave",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "reject-invitation",
		short:       "Reject Organization Invitation",
		operationID: "rejectOrganizationInvitation", method: "POST",
		path:        "/auth/organization/reject-invitation",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "remove-member",
		short:       "Remove Organization Member",
		operationID: "removeOrganizationMember", method: "POST",
		path:        "/auth/organization/remove-member",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "remove-team",
		short:       "Remove Organization Team",
		operationID: "removeOrganizationTeam", method: "POST",
		path:        "/auth/organization/remove-team",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "remove-team-member",
		short:       "Remove Organization Team Member",
		operationID: "removeOrganizationTeamMember", method: "POST",
		path:        "/auth/organization/remove-team-member",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "set-active",
		short:       "Set Organization Active",
		operationID: "setOrganizationActive", method: "POST",
		path: "/auth/organization/set-active",
		body: true,
	},
	{
		group: "org", action: "set-active-team",
		short:       "Set Organization Active Team",
		operationID: "setOrganizationActiveTeam", method: "POST",
		path: "/auth/organization/set-active-team",
		body: true,
	},
	{
		group: "org", action: "update",
		short:       "Update Organization",
		operationID: "updateOrganization", method: "POST",
		path: "/auth/organization/update",
		body: true,
	},
	{
		group: "org", action: "update-member-role",
		short:       "Update Organization Member Role",
		operationID: "updateOrganizationMemberRole", method: "POST",
		path: "/auth/organization/update-member-role",
		body: true,
	},
	{
		group: "org", action: "update-role",
		short:       "Update Organization Role",
		operationID: "updateOrganizationRole", method: "POST",
		path: "/auth/organization/update-role",
		body: true,
	},
	{
		group: "org", action: "update-team",
		short:       "Update Organization Team",
		operationID: "updateOrganizationTeam", method: "POST",
		path: "/auth/organization/update-team",
		body: true,
	},
	{
		group: "project", action: "archive",
		short:       "Archive project",
		operationID: "archiveProject", method: "PUT",
		path: "/project/{id}/archive",
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "project", action: "create",
		short:       "Create project",
		operationID: "createProject", method: "POST",
		path: "/project",
		body: true,
	},
	{
		group: "project", action: "delete",
		short:       "Delete project",
		operationID: "deleteProject", method: "DELETE",
		path:        "/project/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "project", action: "reorder",
		short:       "Reorder projects",
		operationID: "reorderProjects", method: "PUT",
		path: "/project/reorder",
		body: true,
		params: []readParam{
			{name: "workspaceId", in: paramQuery, flag: "workspace-id", required: true},
		},
	},
	{
		group: "project", action: "unarchive",
		short:       "Unarchive project",
		operationID: "unarchiveProject", method: "PUT",
		path: "/project/{id}/unarchive",
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "project", action: "update",
		short:       "Update project",
		operationID: "updateProject", method: "PUT",
		path: "/project/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "slack", action: "create-integration",
		short:       "Create Slack integration",
		operationID: "createSlackIntegration", method: "POST",
		path: "/slack-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "slack", action: "delete-integration",
		short:       "Delete Slack integration",
		operationID: "deleteSlackIntegration", method: "DELETE",
		path:        "/slack-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "slack", action: "update-integration",
		short:       "Update Slack integration",
		operationID: "updateSlackIntegration", method: "PATCH",
		path: "/slack-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "task", action: "bulk-update",
		short:       "Bulk update tasks",
		operationID: "bulkUpdateTasks", method: "PATCH",
		path:        "/task/bulk",
		body:        true,
		destructive: true,
	},
	{
		group: "task", action: "create",
		short:       "Create task",
		operationID: "createTask", method: "POST",
		path:  "/task/{projectId}",
		body:  true,
		notes: `status is a column slug from 'column list', or the reserved value "planned" or "archived" to file the task straight into the Backlog or Archive. Optional draftAssetIds attaches finalized staged assets to the new task.`,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "task", action: "delete",
		short:       "Delete task",
		operationID: "deleteTask", method: "DELETE",
		path:        "/task/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "finalize-image-upload",
		short:       "Finalize image upload",
		operationID: "finalizeTaskImageUpload", method: "POST",
		path: "/task/image-upload/{id}/finalize",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "finalize-staged-asset",
		short:       "Finalize a staged task attachment",
		operationID: "finalizeStagedTaskAsset", method: "POST",
		path: "/task/draft-upload/{projectId}/finalize",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "task", action: "reorder",
		short:       "Reorder or move task cards",
		operationID: "reorderTasks", method: "POST",
		path:  "/task/reorder",
		body:  true,
		notes: `Updates positions and optional column status while preserving all non-position task fields except the requested status. expectedTasks is the previous complete snapshot of affected columns; stale snapshots return HTTP 409. Refresh before reordering; the command never retries.`,
	},
	{
		group: "task", action: "import",
		short:       "Import tasks",
		operationID: "importTasks", method: "POST",
		path:  "/task/import/{projectId}",
		body:  true,
		notes: `An unrecognized status is not rejected: the server rewrites it to "planned" and the task lands in the Backlog. The response still reports success, so read results.tasks[].warnings.`,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "task", action: "move",
		short:       "Move task",
		operationID: "moveTask", method: "PUT",
		path:  "/task/move/{id}",
		body:  true,
		notes: `destinationStatus must be a column slug of the destination project. The reserved values "planned" and "archived" are rejected here, unlike 'task update-status'.`,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update",
		short:       "Update task",
		operationID: "updateTask", method: "PUT",
		path: "/task/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-assignee",
		short:       "Update task assignee",
		operationID: "updateTaskAssignee", method: "PUT",
		path: "/task/assignee/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-description",
		short:       "Update task description",
		operationID: "updateTaskDescription", method: "PUT",
		path: "/task/description/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-due-date",
		short:       "Update task due date",
		operationID: "updateTaskDueDate", method: "PUT",
		path: "/task/due-date/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-priority",
		short:       "Update task priority",
		operationID: "updateTaskPriority", method: "PUT",
		path: "/task/priority/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-status",
		short:       "Update task status",
		operationID: "updateTaskStatus", method: "PUT",
		path:  "/task/status/{id}",
		body:  true,
		notes: `status is a column slug from 'column list', or one of the reserved values "planned" (the Backlog board) or "archived". Any other value is rejected with HTTP 400 and the task is left unchanged.`,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-title",
		short:       "Update task title",
		operationID: "updateTaskTitle", method: "PUT",
		path: "/task/title/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task-relation", action: "create",
		short:       "Create task relation",
		operationID: "createTaskRelation", method: "POST",
		path: "/task-relation",
		body: true,
	},
	{
		group: "task-relation", action: "delete",
		short:       "Delete task relation",
		operationID: "deleteTaskRelation", method: "DELETE",
		path:        "/task-relation/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "telegram", action: "create-integration",
		short:       "Create Telegram integration",
		operationID: "createTelegramIntegration", method: "POST",
		path: "/telegram-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "telegram", action: "delete-integration",
		short:       "Delete Telegram integration",
		operationID: "deleteTelegramIntegration", method: "DELETE",
		path:        "/telegram-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "telegram", action: "update-integration",
		short:       "Update Telegram integration",
		operationID: "updateTelegramIntegration", method: "PATCH",
		path: "/telegram-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "time-entry", action: "create",
		short:       "Create time entry",
		operationID: "createTimeEntry", method: "POST",
		path: "/time-entry",
		body: true,
	},
	{
		group: "time-entry", action: "update",
		short:       "Update time entry",
		operationID: "updateTimeEntry", method: "PUT",
		path: "/time-entry/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "user", action: "delete-avatar",
		short:       "Delete avatar",
		operationID: "deleteUserAvatar", method: "DELETE",
		path:        "/user/avatar",
		destructive: true,
	},
	{
		group: "webhook", action: "create-integration",
		short:       "Create webhook integration",
		operationID: "createGenericWebhookIntegration", method: "POST",
		path: "/generic-webhook-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "webhook", action: "delete-integration",
		short:       "Delete webhook integration",
		operationID: "deleteGenericWebhookIntegration", method: "DELETE",
		path:        "/generic-webhook-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "webhook", action: "update-integration",
		short:       "Update webhook integration",
		operationID: "updateGenericWebhookIntegration", method: "PATCH",
		path: "/generic-webhook-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "workflow-rule", action: "delete",
		short:       "Delete workflow rule",
		operationID: "deleteWorkflowRule", method: "DELETE",
		path:        "/workflow-rule/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "workflow-rule", action: "upsert-project",
		short:       "Upsert workflow rule",
		operationID: "upsertWorkflowRule", method: "PUT",
		path: "/workflow-rule/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "calendar-feed", action: "create",
		short:       "Create a project calendar feed",
		operationID: "createCalendarFeed", method: "POST",
		path:  "/calendar-feed/project/{projectId}",
		body:  true,
		notes: `The response contains the secret feed token. Anyone with the token can read the feed, so store it like a password. This is the only command that shows it: 'calendar-feed list' redacts it. Use 'calendar-feed download --token-file' to fetch the feed.`,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "calendar-feed", action: "revoke",
		short:       "Revoke a project calendar feed",
		operationID: "revokeCalendarFeed", method: "DELETE",
		path:        "/calendar-feed/project/{projectId}/{id}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "external-link", action: "create",
		short:       "Create task external link",
		operationID: "createExternalLink", method: "POST",
		path: "/external-link/task/{taskId}",
		body: true,
		params: []readParam{
			{name: "taskId", in: paramPath, flag: "task-id", required: true},
		},
	},
	{
		group: "external-link", action: "delete",
		short:       "Delete task external link",
		operationID: "deleteExternalLink", method: "DELETE",
		path:        "/external-link/task/{taskId}/{id}",
		destructive: true,
		params: []readParam{
			{name: "taskId", in: paramPath, flag: "task-id", required: true},
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "gitlab", action: "create-integration",
		short:       "Create GitLab integration",
		operationID: "createGitlabIntegration", method: "POST",
		path: "/gitlab-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitlab", action: "delete-integration",
		short:       "Delete GitLab integration",
		operationID: "deleteGitlabIntegration", method: "DELETE",
		path:        "/gitlab-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitlab", action: "import-issues",
		short:       "Import GitLab issues",
		operationID: "importGitlabIssues", method: "POST",
		path:  "/gitlab-integration/import-issues",
		body:  true,
		notes: `Requires task:update permission in addition to task:create. When the result reports a non-empty errors array, the command prints the complete result on stdout and exits 5 with error code "partial_failure".`,
	},
	{
		group: "gitlab", action: "list-projects",
		short:       "List GitLab projects",
		operationID: "listGitlabProjects", method: "POST",
		path: "/gitlab-integration/projects",
		body: true,
	},
	{
		group: "gitlab", action: "update-integration",
		short:       "Update GitLab integration",
		operationID: "updateGitlabIntegration", method: "PATCH",
		path: "/gitlab-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitlab", action: "verify-access",
		short:       "Verify GitLab access",
		operationID: "verifyGitlabAccess", method: "POST",
		path: "/gitlab-integration/verify",
		body: true,
	},
	{
		group: "project", action: "delete-background",
		short:       "Delete project background",
		operationID: "deleteProjectBackground", method: "DELETE",
		path:        "/project/{id}/background",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "project", action: "finalize-background-upload",
		short:       "Finalize project background upload",
		operationID: "finalizeProjectBackgroundUpload", method: "POST",
		path: "/project/{id}/background-upload/finalize",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "project", action: "move",
		short:       "Move project",
		operationID: "moveProject", method: "PUT",
		path:        "/project/{id}/move",
		body:        true,
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "duplicate",
		short:       "Duplicate a task",
		operationID: "duplicateTask", method: "POST",
		path: "/task/duplicate/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "admin", action: "add-workspace-member",
		short:       "Add a user to a workspace",
		operationID: "addAdminWorkspaceMember", method: "POST",
		path:  "/admin/workspaces/{workspaceId}/members",
		body:  true,
		notes: "Requires an instance administrator session token; API keys are rejected. The member starts with access to every project.",
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
		},
	},
	{
		group: "admin", action: "remove-workspace-member",
		short:       "Remove a workspace member",
		operationID: "removeAdminWorkspaceMember", method: "DELETE",
		path:        "/admin/workspaces/{workspaceId}/members/{userId}",
		destructive: true,
		notes:       "Requires an instance administrator session token; API keys are rejected. Removes membership, not the user account.",
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
			{name: "userId", in: paramPath, flag: "user-id", required: true},
		},
	},
	{
		group: "admin", action: "update-workspace-member-role",
		short:       "Change a workspace member's role",
		operationID: "updateAdminWorkspaceMemberRole", method: "PUT",
		path:  "/admin/workspaces/{workspaceId}/members/{userId}/role",
		body:  true,
		notes: "Requires an instance administrator session token; API keys are rejected. Use transfer-workspace-ownership to make a member the owner.",
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
			{name: "userId", in: paramPath, flag: "user-id", required: true},
		},
	},
	{
		group: "admin", action: "transfer-workspace-ownership",
		short:       "Transfer workspace ownership",
		operationID: "transferAdminWorkspaceOwnership", method: "PUT",
		path:        "/admin/workspaces/{workspaceId}/owner",
		body:        true,
		destructive: true,
		notes:       "Requires an instance administrator session token; API keys are rejected. Makes an existing member the only owner; previous owners become admins.",
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
		},
	},
	{
		group: "workspace", action: "update-member-project-access",
		short:       "Update member project access",
		operationID: "updateMemberProjectAccess", method: "PUT",
		path:        "/workspace/{workspaceId}/members/{userId}/project-access",
		body:        true,
		destructive: true,
		notes:       "Can revoke project access. Owners always access every project; you cannot change your own access or grant projects you cannot access.",
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
			{name: "userId", in: paramPath, flag: "user-id", required: true},
		},
	},
	{
		group: "integration-sync", action: "preview-rules",
		short:       "Preview a sync rule change",
		operationID: "previewIntegrationSyncRules", method: "POST",
		path:  "/integration-sync/project/{projectId}/{provider}/preview",
		body:  true,
		notes: "Preview first, then pass the rules and returned previewToken to save-rules. Outgoing labels are workspace label IDs; incoming labels are exact repository label names. Tokens are comparison tokens, not credentials. Conflicts are not retried.",
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true, minLen: 1},
			{name: "provider", in: paramPath, flag: "provider", required: true, enum: []string{"github", "gitea", "gitlab"}},
		},
	},
	{
		group: "integration-sync", action: "save-rules",
		short:       "Apply a previewed sync rule",
		operationID: "saveIntegrationSyncRules", method: "PATCH",
		path:  "/integration-sync/project/{projectId}/{provider}",
		body:  true,
		notes: "Run preview-rules first and submit its rules and previewToken. Excluded links are paused, never deleted; paused links require review-resume before resume. A stale preview returns HTTP 409: preview again. The command never retries.",
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true, minLen: 1},
			{name: "provider", in: paramPath, flag: "provider", required: true, enum: []string{"github", "gitea", "gitlab"}},
		},
	},
	{
		group: "integration-sync", action: "resume",
		short:       "Resume a reviewed issue link",
		operationID: "resumeIntegrationSync", method: "POST",
		path:        "/integration-sync/project/{projectId}/{provider}/links/{linkId}/resume",
		body:        true,
		destructive: true,
		notes:       "Run review-resume first, then submit its comparison token and choose source kaneo or provider. Requires --yes because the chosen title, description and open/closed state overwrite the other side. Reuses the paused link without replaying historical comments. A changed comparison requires another review; HTTP 409/502 are never retried and failures leave sync paused.",
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true, minLen: 1},
			{name: "provider", in: paramPath, flag: "provider", required: true, enum: []string{"github", "gitea", "gitlab"}},
			{name: "linkId", in: paramPath, flag: "link-id", required: true, minLen: 1},
		},
	},
}
