package cli

// Mutating operation table for packet 3 coverage, derived from
// api/operations.json (the pinned OpenAPI inventory). write_ops_test.go fails
// if this table drifts from the inventory or leaves a non-GET operation
// uncovered. Two presigned/base64 upload operations use dedicated commands and
// are listed in writeSpecExempt; the two browser-navigation GET operations are
// deferred with the read table.

// writeSpecs maps every implemented mutating operation to a CLI command.
var writeSpecs = []writeSpec{
	{
		group: "activity", action: "create",
		short:       "Create activity",
		operationID: "createActivity", method: "POST",
		path: "/activity/create",
		body: true,
	},
	{
		group: "activity", action: "create-comment",
		short:       "Create comment",
		operationID: "createComment", method: "POST",
		path: "/activity/comment",
		body: true,
	},
	{
		group: "activity", action: "delete-comment",
		short:       "Delete comment",
		operationID: "deleteComment", method: "DELETE",
		path:        "/activity/comment",
		body:        true,
		destructive: true,
	},
	{
		group: "activity", action: "update-comment",
		short:       "Update comment",
		operationID: "updateComment", method: "PUT",
		path: "/activity/comment",
		body: true,
	},
	{
		group: "column", action: "create",
		short:       "Create column",
		operationID: "createColumn", method: "POST",
		path: "/column/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "column", action: "delete",
		short:       "Delete column",
		operationID: "deleteColumn", method: "DELETE",
		path:        "/column/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "column", action: "reorder",
		short:       "Reorder columns",
		operationID: "reorderColumns", method: "PUT",
		path: "/column/reorder/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "column", action: "update",
		short:       "Update column",
		operationID: "updateColumn", method: "PUT",
		path: "/column/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "comment", action: "create-task",
		short:       "Create task comment",
		operationID: "createTaskComment", method: "POST",
		path: "/comment/{taskId}",
		body: true,
		params: []readParam{
			{name: "taskId", in: paramPath, flag: "task-id", required: true},
		},
	},
	{
		group: "comment", action: "delete",
		short:       "Delete task comment",
		operationID: "deleteTaskComment", method: "DELETE",
		path:        "/comment/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "comment", action: "update",
		short:       "Update task comment",
		operationID: "updateTaskComment", method: "PUT",
		path: "/comment/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "custom-field", action: "create",
		short:       "Create custom field",
		operationID: "createCustomField", method: "POST",
		path: "/custom-field",
		body: true,
	},
	{
		group: "custom-field", action: "delete",
		short:       "Delete custom field",
		operationID: "deleteCustomField", method: "DELETE",
		path:        "/custom-field/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "custom-field", action: "reorder-project",
		short:       "Reorder custom fields",
		operationID: "reorderCustomFields", method: "PUT",
		path: "/custom-field/reorder/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "custom-field", action: "set-value",
		short:       "Set custom field value",
		operationID: "setCustomFieldValue", method: "PUT",
		path: "/custom-field/value",
		body: true,
	},
	{
		group: "discord", action: "create-integration",
		short:       "Create Discord integration",
		operationID: "createDiscordIntegration", method: "POST",
		path: "/discord-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "discord", action: "delete-integration",
		short:       "Delete Discord integration",
		operationID: "deleteDiscordIntegration", method: "DELETE",
		path:        "/discord-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "discord", action: "update-integration",
		short:       "Update Discord integration",
		operationID: "updateDiscordIntegration", method: "PATCH",
		path: "/discord-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitea", action: "create-integration",
		short:       "Create Gitea integration",
		operationID: "createGiteaIntegration", method: "POST",
		path: "/gitea-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitea", action: "delete-integration",
		short:       "Delete Gitea integration",
		operationID: "deleteGiteaIntegration", method: "DELETE",
		path:        "/gitea-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitea", action: "import-issues",
		short:       "Import Gitea issues",
		operationID: "importGiteaIssues", method: "POST",
		path: "/gitea-integration/import-issues",
		body: true,
	},
	{
		group: "gitea", action: "list-repositories",
		short:       "List Gitea repositories",
		operationID: "listGiteaRepositories", method: "POST",
		path: "/gitea-integration/repositories",
		body: true,
	},
	{
		group: "gitea", action: "update-integration",
		short:       "Update Gitea integration",
		operationID: "updateGiteaIntegration", method: "PATCH",
		path: "/gitea-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "gitea", action: "verify-access",
		short:       "Verify Gitea access",
		operationID: "verifyGiteaAccess", method: "POST",
		path: "/gitea-integration/verify",
		body: true,
	},
	{
		group: "github", action: "create-integration",
		short:       "Create GitHub integration",
		operationID: "createGitHubIntegration", method: "POST",
		path: "/github-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "github", action: "delete-integration",
		short:       "Delete GitHub integration",
		operationID: "deleteGitHubIntegration", method: "DELETE",
		path:        "/github-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "github", action: "import-issues",
		short:       "Import GitHub issues",
		operationID: "importGitHubIssues", method: "POST",
		path: "/github-integration/import-issues",
		body: true,
	},
	{
		group: "github", action: "update-integration",
		short:       "Update GitHub integration",
		operationID: "updateGitHubIntegration", method: "PATCH",
		path: "/github-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "github", action: "verify-installation",
		short:       "Verify GitHub installation",
		operationID: "verifyGitHubInstallation", method: "POST",
		path: "/github-integration/verify",
		body: true,
	},
	{
		group: "label", action: "attach-task",
		short:       "Attach label to task",
		operationID: "attachLabelToTask", method: "PUT",
		path: "/label/{id}/task",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "label", action: "create",
		short:       "Create label",
		operationID: "createLabel", method: "POST",
		path: "/label",
		body: true,
	},
	{
		group: "label", action: "delete",
		short:       "Delete label",
		operationID: "deleteLabel", method: "DELETE",
		path:        "/label/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "label", action: "detach-task",
		short:       "Detach label from task",
		operationID: "detachLabelFromTask", method: "DELETE",
		path:        "/label/{id}/task",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "label", action: "update",
		short:       "Update label",
		operationID: "updateLabel", method: "PUT",
		path: "/label/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "mattermost", action: "create-integration",
		short:       "Create Mattermost integration",
		operationID: "createMattermostIntegration", method: "POST",
		path: "/mattermost-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "mattermost", action: "delete-integration",
		short:       "Delete Mattermost integration",
		operationID: "deleteMattermostIntegration", method: "DELETE",
		path:        "/mattermost-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "mattermost", action: "update-integration",
		short:       "Update Mattermost integration",
		operationID: "updateMattermostIntegration", method: "PATCH",
		path: "/mattermost-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "mcp", action: "decide-authorization-request",
		short:       "Decide consent request",
		operationID: "decideMcpAuthorizationRequest", method: "POST",
		path: "/mcp/authorize/request/{requestId}",
		body: true,
		params: []readParam{
			{name: "requestId", in: paramPath, flag: "request-id", required: true},
		},
	},
	{
		group: "mcp", action: "register-oauth-client",
		short:       "Register MCP OAuth client",
		operationID: "registerMcpOAuthClient", method: "POST",
		path:   "/mcp/register",
		public: true,
		body:   true,
	},
	{
		group: "notification", action: "clear-all",
		short:       "Clear all",
		operationID: "clearAllNotifications", method: "DELETE",
		path:        "/notification/clear-all",
		destructive: true,
	},
	{
		group: "notification", action: "create",
		short:       "Create notification",
		operationID: "createNotification", method: "POST",
		path: "/notification",
		body: true,
	},
	{
		group: "notification", action: "mark-all-read",
		short:       "Mark all read",
		operationID: "markAllNotificationsAsRead", method: "PATCH",
		path: "/notification/read-all",
	},
	{
		group: "notification", action: "mark-read",
		short:       "Mark notification read",
		operationID: "markNotificationAsRead", method: "PATCH",
		path: "/notification/{id}/read",
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "notification-preference", action: "delete-workspace-rule",
		short:       "Delete workspace rule",
		operationID: "deleteNotificationPreferenceWorkspaceRule", method: "DELETE",
		path:        "/notification-preferences/workspaces/{workspaceId}",
		destructive: true,
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
		},
	},
	{
		group: "notification-preference", action: "update",
		short:       "Update notification preferences",
		operationID: "updateNotificationPreferences", method: "PUT",
		path: "/notification-preferences",
		body: true,
	},
	{
		group: "notification-preference", action: "upsert-workspace-rule",
		short:       "Upsert workspace rule",
		operationID: "upsertNotificationPreferenceWorkspaceRule", method: "PUT",
		path: "/notification-preferences/workspaces/{workspaceId}",
		body: true,
		params: []readParam{
			{name: "workspaceId", in: paramPath, flag: "workspace-id", required: true},
		},
	},
	{
		group: "org", action: "accept-invitation",
		short:       "Accept Organization Invitation",
		operationID: "acceptOrganizationInvitation", method: "POST",
		path: "/auth/organization/accept-invitation",
		body: true,
	},
	{
		group: "org", action: "add-team-member",
		short:       "Add Organization Team Member",
		operationID: "addOrganizationTeamMember", method: "POST",
		path: "/auth/organization/add-team-member",
		body: true,
	},
	{
		group: "org", action: "cancel-invitation",
		short:       "Cancel Organization Invitation",
		operationID: "cancelOrganizationInvitation", method: "POST",
		path:        "/auth/organization/cancel-invitation",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "check-permission",
		short:       "Check Organization Permission",
		operationID: "hasOrganizationPermission", method: "POST",
		path: "/auth/organization/has-permission",
		body: true,
	},
	{
		group: "org", action: "check-slug",
		short:       "Check Organization Slug",
		operationID: "checkOrganizationSlug", method: "POST",
		path: "/auth/organization/check-slug",
		body: true,
	},
	{
		group: "org", action: "create",
		short:       "Create Organization",
		operationID: "createOrganization", method: "POST",
		path: "/auth/organization/create",
		body: true,
	},
	{
		group: "org", action: "create-role",
		short:       "Create Organization Role",
		operationID: "createOrganizationRole", method: "POST",
		path: "/auth/organization/create-role",
		body: true,
	},
	{
		group: "org", action: "create-team",
		short:       "Create Organization Team",
		operationID: "createOrganizationTeam", method: "POST",
		path: "/auth/organization/create-team",
		body: true,
	},
	{
		group: "org", action: "delete",
		short:       "Delete Organization",
		operationID: "deleteOrganization", method: "POST",
		path:        "/auth/organization/delete",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "delete-role",
		short:       "Delete Organization Role",
		operationID: "deleteOrganizationRole", method: "POST",
		path:        "/auth/organization/delete-role",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "invite-member",
		short:       "Invite Organization Member",
		operationID: "inviteOrganizationMember", method: "POST",
		path: "/auth/organization/invite-member",
		body: true,
	},
	{
		group: "org", action: "leave",
		short:       "Leave Organization",
		operationID: "leaveOrganization", method: "POST",
		path:        "/auth/organization/leave",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "reject-invitation",
		short:       "Reject Organization Invitation",
		operationID: "rejectOrganizationInvitation", method: "POST",
		path:        "/auth/organization/reject-invitation",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "remove-member",
		short:       "Remove Organization Member",
		operationID: "removeOrganizationMember", method: "POST",
		path:        "/auth/organization/remove-member",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "remove-team",
		short:       "Remove Organization Team",
		operationID: "removeOrganizationTeam", method: "POST",
		path:        "/auth/organization/remove-team",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "remove-team-member",
		short:       "Remove Organization Team Member",
		operationID: "removeOrganizationTeamMember", method: "POST",
		path:        "/auth/organization/remove-team-member",
		body:        true,
		destructive: true,
	},
	{
		group: "org", action: "set-active",
		short:       "Set Organization Active",
		operationID: "setOrganizationActive", method: "POST",
		path: "/auth/organization/set-active",
		body: true,
	},
	{
		group: "org", action: "set-active-team",
		short:       "Set Organization Active Team",
		operationID: "setOrganizationActiveTeam", method: "POST",
		path: "/auth/organization/set-active-team",
		body: true,
	},
	{
		group: "org", action: "update",
		short:       "Update Organization",
		operationID: "updateOrganization", method: "POST",
		path: "/auth/organization/update",
		body: true,
	},
	{
		group: "org", action: "update-member-role",
		short:       "Update Organization Member Role",
		operationID: "updateOrganizationMemberRole", method: "POST",
		path: "/auth/organization/update-member-role",
		body: true,
	},
	{
		group: "org", action: "update-role",
		short:       "Update Organization Role",
		operationID: "updateOrganizationRole", method: "POST",
		path: "/auth/organization/update-role",
		body: true,
	},
	{
		group: "org", action: "update-team",
		short:       "Update Organization Team",
		operationID: "updateOrganizationTeam", method: "POST",
		path: "/auth/organization/update-team",
		body: true,
	},
	{
		group: "project", action: "archive",
		short:       "Archive project",
		operationID: "archiveProject", method: "PUT",
		path: "/project/{id}/archive",
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "project", action: "create",
		short:       "Create project",
		operationID: "createProject", method: "POST",
		path: "/project",
		body: true,
	},
	{
		group: "project", action: "delete",
		short:       "Delete project",
		operationID: "deleteProject", method: "DELETE",
		path:        "/project/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "project", action: "reorder",
		short:       "Reorder projects",
		operationID: "reorderProjects", method: "PUT",
		path: "/project/reorder",
		body: true,
		params: []readParam{
			{name: "workspaceId", in: paramQuery, flag: "workspace-id", required: true},
		},
	},
	{
		group: "project", action: "unarchive",
		short:       "Unarchive project",
		operationID: "unarchiveProject", method: "PUT",
		path: "/project/{id}/unarchive",
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "project", action: "update",
		short:       "Update project",
		operationID: "updateProject", method: "PUT",
		path: "/project/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "slack", action: "create-integration",
		short:       "Create Slack integration",
		operationID: "createSlackIntegration", method: "POST",
		path: "/slack-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "slack", action: "delete-integration",
		short:       "Delete Slack integration",
		operationID: "deleteSlackIntegration", method: "DELETE",
		path:        "/slack-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "slack", action: "update-integration",
		short:       "Update Slack integration",
		operationID: "updateSlackIntegration", method: "PATCH",
		path: "/slack-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "task", action: "bulk-update",
		short:       "Bulk update tasks",
		operationID: "bulkUpdateTasks", method: "PATCH",
		path:        "/task/bulk",
		body:        true,
		destructive: true,
	},
	{
		group: "task", action: "create",
		short:       "Create task",
		operationID: "createTask", method: "POST",
		path: "/task/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "task", action: "delete",
		short:       "Delete task",
		operationID: "deleteTask", method: "DELETE",
		path:        "/task/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "finalize-image-upload",
		short:       "Finalize image upload",
		operationID: "finalizeTaskImageUpload", method: "POST",
		path: "/task/image-upload/{id}/finalize",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "import",
		short:       "Import tasks",
		operationID: "importTasks", method: "POST",
		path: "/task/import/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "task", action: "move",
		short:       "Move task",
		operationID: "moveTask", method: "PUT",
		path: "/task/move/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update",
		short:       "Update task",
		operationID: "updateTask", method: "PUT",
		path: "/task/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-assignee",
		short:       "Update task assignee",
		operationID: "updateTaskAssignee", method: "PUT",
		path: "/task/assignee/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-description",
		short:       "Update task description",
		operationID: "updateTaskDescription", method: "PUT",
		path: "/task/description/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-due-date",
		short:       "Update task due date",
		operationID: "updateTaskDueDate", method: "PUT",
		path: "/task/due-date/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-priority",
		short:       "Update task priority",
		operationID: "updateTaskPriority", method: "PUT",
		path: "/task/priority/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-status",
		short:       "Update task status",
		operationID: "updateTaskStatus", method: "PUT",
		path: "/task/status/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task", action: "update-title",
		short:       "Update task title",
		operationID: "updateTaskTitle", method: "PUT",
		path: "/task/title/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "task-relation", action: "create",
		short:       "Create task relation",
		operationID: "createTaskRelation", method: "POST",
		path: "/task-relation",
		body: true,
	},
	{
		group: "task-relation", action: "delete",
		short:       "Delete task relation",
		operationID: "deleteTaskRelation", method: "DELETE",
		path:        "/task-relation/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "telegram", action: "create-integration",
		short:       "Create Telegram integration",
		operationID: "createTelegramIntegration", method: "POST",
		path: "/telegram-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "telegram", action: "delete-integration",
		short:       "Delete Telegram integration",
		operationID: "deleteTelegramIntegration", method: "DELETE",
		path:        "/telegram-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "telegram", action: "update-integration",
		short:       "Update Telegram integration",
		operationID: "updateTelegramIntegration", method: "PATCH",
		path: "/telegram-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "time-entry", action: "create",
		short:       "Create time entry",
		operationID: "createTimeEntry", method: "POST",
		path: "/time-entry",
		body: true,
	},
	{
		group: "time-entry", action: "update",
		short:       "Update time entry",
		operationID: "updateTimeEntry", method: "PUT",
		path: "/time-entry/{id}",
		body: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "user", action: "delete-avatar",
		short:       "Delete avatar",
		operationID: "deleteUserAvatar", method: "DELETE",
		path:        "/user/avatar",
		destructive: true,
	},
	{
		group: "webhook", action: "create-integration",
		short:       "Create webhook integration",
		operationID: "createGenericWebhookIntegration", method: "POST",
		path: "/generic-webhook-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "webhook", action: "delete-integration",
		short:       "Delete webhook integration",
		operationID: "deleteGenericWebhookIntegration", method: "DELETE",
		path:        "/generic-webhook-integration/project/{projectId}",
		destructive: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "webhook", action: "update-integration",
		short:       "Update webhook integration",
		operationID: "updateGenericWebhookIntegration", method: "PATCH",
		path: "/generic-webhook-integration/project/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
	{
		group: "workflow-rule", action: "delete",
		short:       "Delete workflow rule",
		operationID: "deleteWorkflowRule", method: "DELETE",
		path:        "/workflow-rule/{id}",
		destructive: true,
		params: []readParam{
			{name: "id", in: paramPath, flag: "id", required: true},
		},
	},
	{
		group: "workflow-rule", action: "upsert-project",
		short:       "Upsert workflow rule",
		operationID: "upsertWorkflowRule", method: "PUT",
		path: "/workflow-rule/{projectId}",
		body: true,
		params: []readParam{
			{name: "projectId", in: paramPath, flag: "project-id", required: true},
		},
	},
}
